# 应用服务 WEB 访问端口
server:
  port: 8080
# 应用名称
spring:
  application:
    name: spring-redis-lua
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-active: 10
        max-idle: 3
        max-wait: 3
        min-idle: 1



